apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-instance-controller
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-instance-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-instance-controller
    spec:
      containers:
      - name: {{ .Release.Name }}-instance-controller
        image: {{ include "unikorn.computeInstanceControllerImage" . }}
        args:
        - --namespace={{ .Release.Namespace }}
        {{- include "unikorn.identity.flags" . | nindent 8 }}
        {{- include "unikorn.region.flags" . | nindent 8 }}
        {{- include "unikorn.otlp.flags" . | nindent 8 }}
        {{- include "unikorn.mtls.flags" . | nindent 8 }}
        ports:
        - name: prometheus
          containerPort: 8080
        resources:
          {{- .Values.instanceController.resources | toYaml | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
      serviceAccountName: {{ .Release.Name }}-instance-controller
      securityContext:
        runAsNonRoot: true
